### ISSUE TITLE
Perform Actions when a Option Button is tapped

### ISSUE THREAD

**Issue by ghost** [vladislav-k/VKExpandableButton#3]
I can't understand how to perform an action when a button inside the option view is tapped, how can I do that?

**Comment by vladislav-k** [comment]
Hi @AaronLatnok,

you can check what button was tapped with `optionSelectionBlock`. This block is being called when any button was tapped and it gives you button index, so you can determine what exact button was it. You check the [example code](https://github.com/vladislav-k/VKExpandableButton#example).

Thanks

**Comment by ghost** [comment]
I'm sorry, I have been too much generic with the question. What I want to do is a performSegue when I click a specific button. I dont'have problem for example to change the color of the background,but I don't know what I have to put in the segue: field. I have written:
`self.buttonRight.optionSelectionBlock = {
            index in
            print("[Right] Did select option at index: \(index)")
            if index == 2
            {
                self.performSegue(withIdentifier: "green", sender: self.buttonRight.optionSelectionBlock)
            }
        }`
The project run but when I touch the button the app crashes.
I hope in an your advice, thank you for the support and the patience

**Comment by vladislav-k** [comment]
This is not related to the control itself, but ok. First of all, you don't need to send `self.buttonRight.optionSelectionBlock` as `sender:`. Also you should check that your control has segue with name "green" and check what is expected in `prepareForSegue:` feature. After all, it is better you to read [this article](https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/UsingSegues.html).
