### ISSUE TITLE
Getting memory leaks

### ISSUE THREAD

**Issue by mohamedrafiba** [vladislav-k/VKExpandableButton#4]
Getting many memory leaks when click on show option button. Please help.

**Comment by vladislav-k** [comment]
Use `unowned` or `weak` flags inside of the completion closure:

`self.buttonRight.optionSelectionBlock = {
	[weak self] index in
	print("[Right] Did select option at index: \(index)")
}`

OR

`self.buttonRight.optionSelectionBlock = {
	[unowned self] index in
	print("[Right] Did select option at index: \(index)")
}`
